services:
  viaggia-api:
    image: victorhpmelo/viaggia-api:${VERSION:-0.1.1}
    build:
      context: ..                 # raiz do repositório (importante!)
      dockerfile: docker/Dockerfile
      args:
        APP_VERSION: ${VERSION:-0.1.1}
    container_name: viaggia-api
    env_file:
      - ../.env                   # .env está na raiz
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
