services:
  viaggia-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    container_name: viaggia-backend
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "7164:8080"
    volumes:
      - ../:/app
      - uploads:/app/wwwroot/Uploads
    networks:
      - viaggia-network

networks:
  viaggia-network:
    external: true

volumes:
  uploads:
