name: Viaggia CI - Build and Test

on:
    push:
        branches:
            - main
            - main-dev
            - test
            - main-Victor
            - test-Victor
    pull_request:
        branches:
            - main
            - main-dev
            - test
            - test-Victor
            - main-Victor

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build the project
              run: dotnet build --no-restore

            - name: Run tests
              run: dotnet test --no-build --verbosity normal

    docker-build:
        runs-on: ubuntu-latest
        needs: build-and-test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image (dev)
              run: |
                  cd docker
                  docker build -f Dockerfile.dev -t viaggia-backend:dev ..

            - name: Test Docker container
              run: |
                  docker run --rm -d --name test-backend -p 7164:8080 \
                    -e ASPNETCORE_ENVIRONMENT=Development \
                    viaggia-backend:dev
                  sleep 20
                  # Test if the container is running (simple health check)
                  docker logs test-backend
                  # Check if the process is still running
                  docker ps | grep test-backend || exit 1
                  docker stop test-backend